package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.CmsArticle;
import com.briup.apps.cms.bean.CmsArticleWithBLOBs;

public interface CmsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated Tue Nov 12 16:39:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated Tue Nov 12 16:39:53 CST 2019
     */
    int insert(CmsArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated Tue Nov 12 16:39:53 CST 2019
     */
    int insertSelective(CmsArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated Tue Nov 12 16:39:53 CST 2019
     */
    CmsArticleWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated Tue Nov 12 16:39:53 CST 2019
     */
    int updateByPrimaryKeySelective(CmsArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated Tue Nov 12 16:39:53 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CmsArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated Tue Nov 12 16:39:53 CST 2019
     */
    int updateByPrimaryKey(CmsArticle record);
}