package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.CmsPrivilege;

public interface CmsPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insert(CmsPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insertSelective(CmsPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    CmsPrivilege selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKeySelective(CmsPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CmsPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKey(CmsPrivilege record);
}