package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.CmsRolePrivilege;

public interface CmsRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insert(CmsRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insertSelective(CmsRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    CmsRolePrivilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKeySelective(CmsRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKey(CmsRolePrivilege record);
}