package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.CmsRole;

public interface CmsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insert(CmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insertSelective(CmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    CmsRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKeySelective(CmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKey(CmsRole record);
}