package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.CmsUser;

public interface CmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insert(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insertSelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    CmsUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKeySelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKey(CmsUser record);
}