package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.CmsUserRole;

public interface CmsUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insert(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int insertSelective(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    CmsUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKeySelective(CmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 16:35:38 CST 2019
     */
    int updateByPrimaryKey(CmsUserRole record);
}